/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Cursor;
import java.awt.FlowLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.AllSystem;
import model.Appointment;
import model.Community;
import model.CommunityAdmin;
import model.Hospital;
import model.HospitalDirectory;
import model.House;
import model.Person;

/**
 *
 * @author evelynzu
 */


public class CommunityAdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CommunityAdminJFrame
     */
    
    FlowLayout mainLayout = new FlowLayout();
    DefaultTableModel hospitalmodel;
    TableRowSorter hospitalTableRowSorter;
    DefaultTableModel housemodel;
    TableRowSorter houseTableRowSorter;
    
 
    static CommunityAdmin communityAdmin;
    public CommunityAdminJFrame(CommunityAdmin communityAdmin) {
        this.communityAdmin = AllSystem.communityAdmin1;
        initComponents();
        lbLogout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        populateTableHouse();
        houseTableRowSorter = new TableRowSorter(housemodel);
        tblHouse.setRowSorter(houseTableRowSorter);
        
        
        populateTableHospital();
        hospitalTableRowSorter = new TableRowSorter(hospitalmodel);
        tblHospital.setRowSorter(hospitalTableRowSorter);
//        sort(hospitalTableRowSorter, hospitalmodel, tblHospital);

        setLayout(mainLayout);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        btnEditHospital = new javax.swing.JButton();
        btnHouse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHouse = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfNewHospital = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSaveHospital = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfHouse = new javax.swing.JTextField();
        btnSaveNewHouse = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfOwner = new javax.swing.JTextField();
        tfSearchHospital = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfHousesearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(189, 212, 231));

        startPanel.setBackground(new java.awt.Color(189, 212, 231));

        btnEditHospital.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnEditHospital.setText("Edit hospital");
        btnEditHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHospitalActionPerformed(evt);
            }
        });

        btnHouse.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnHouse.setText("Edit house");
        btnHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHouseActionPerformed(evt);
            }
        });

        tblHouse.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tblHouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "House", "Owner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHouseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHouse);

        tblHospital.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tblHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Hospital"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHospitalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHospital);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("hospital:");

        tfNewHospital.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel3.setText("New hopspital");

        btnSaveHospital.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnSaveHospital.setText("Save");
        btnSaveHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveHospitalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("address:");

        tfHouse.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        btnSaveNewHouse.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnSaveNewHouse.setText("Save");
        btnSaveNewHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewHouseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("owner:");

        tfOwner.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        tfSearchHospital.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tfSearchHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchHospitalActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfHousesearch.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setText("Hospital");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel11.setText("House");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setText("New hopspital");

        lbLogout.setText("Logout");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNewHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSaveHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfSearchHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfHousesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEditHospital)
                                    .addComponent(btnHouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfOwner)
                                    .addComponent(tfHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnSaveNewHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(0, 872, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogout)
                .addGap(34, 34, 34))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lbLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditHospital)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                                .addComponent(tfSearchHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))
                        .addComponent(jLabel3)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHouse))
                            .addGroup(startPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tfNewHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSaveHospital))
                                .addGap(110, 110, 110)
                                .addComponent(tfHousesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel7)))
                        .addGap(26, 26, 26)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveNewHouse)))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHospitalActionPerformed
        try {
            int selectedRowIndex =tblHospital.getSelectedRow();
        hospitalmodel = (DefaultTableModel) tblHospital.getModel();
        Hospital hospital = (Hospital)hospitalmodel.getValueAt(tblHospital.convertRowIndexToModel(selectedRowIndex), 0);
        CommunityAdminHospitalJPanel communityAdminHospitalJPanel = new CommunityAdminHospitalJPanel(communityAdmin, hospital);
        add(communityAdminHospitalJPanel);
        communityAdminHospitalJPanel.setVisible(true);
        startPanel.setVisible(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a hospital first");
        }

    }//GEN-LAST:event_btnEditHospitalActionPerformed

    private void btnHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseActionPerformed
        try{
            int selectedRowIndex = tblHouse.getSelectedRow();
        housemodel = (DefaultTableModel) tblHouse.getModel();
        House house = (House)housemodel.getValueAt(tblHouse.convertRowIndexToModel(selectedRowIndex), 0);
        CommunityAdminHouseJPanel communityAdminHouseJPanel = new CommunityAdminHouseJPanel(communityAdmin, house);
        add(communityAdminHouseJPanel);
        communityAdminHouseJPanel.setVisible(true);
        startPanel.setVisible(false);
            
        } catch(Exception exception){
            JOptionPane.showMessageDialog(this, "Please select a house first");
        }
        
        
    }//GEN-LAST:event_btnHouseActionPerformed

    private void btnSaveHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveHospitalActionPerformed
        String hospitalName = tfNewHospital.getText();
        Hospital newHospital = new Hospital(hospitalName);
        HospitalDirectory hospitalDirectory = new HospitalDirectory();
        communityAdmin.getCommunity().getHospitalDirectory().addNewHospital(newHospital);
        populateTableHospital();
        tfNewHospital.setText("");
        
    }//GEN-LAST:event_btnSaveHospitalActionPerformed

    private void btnSaveNewHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewHouseActionPerformed
        String address = tfHouse.getText();
        String owner = tfOwner.getText();
        House newHouse = new House(address, owner,new ArrayList<>());
        communityAdmin.getCommunity().getHouses().add(newHouse);
        populateTableHouse();
        tfHouse.setText("");
        tfOwner.setText("");
    }//GEN-LAST:event_btnSaveNewHouseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String text = tfSearchHospital.getText();
        if (text.trim().length() == 0) {
    hospitalTableRowSorter.setRowFilter(null);
  } else {
     hospitalTableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
  }
        tblHospital.getRowSorter();
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfSearchHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchHospitalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String text = tfHousesearch.getText();
        if (text.trim().length() == 0) {
    houseTableRowSorter.setRowFilter(null);
  } else {
     houseTableRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
  }
        tblHouse.getRowSorter();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblHouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHouseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHouseMouseClicked

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        LoginJframe loginJframe = new LoginJframe();
        loginJframe.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void tblHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHospitalMouseClicked
        int selectedRow = tblHospital.getSelectedRow();
       
        Hospital selectedHospital = (Hospital)hospitalmodel.getValueAt(tblHospital.convertRowIndexToModel(selectedRow), 0);
        
        tfSearchHospital.setText(selectedHospital.getName());
    }//GEN-LAST:event_tblHospitalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommunityAdminJFrame(communityAdmin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditHospital;
    private javax.swing.JButton btnHouse;
    private javax.swing.JButton btnSaveHospital;
    private javax.swing.JButton btnSaveNewHouse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JPanel startPanel;
    private javax.swing.JTable tblHospital;
    private javax.swing.JTable tblHouse;
    private javax.swing.JTextField tfHouse;
    private javax.swing.JTextField tfHousesearch;
    private javax.swing.JTextField tfNewHospital;
    private javax.swing.JTextField tfOwner;
    private javax.swing.JTextField tfSearchHospital;
    // End of variables declaration//GEN-END:variables

    private void populateTableHouse() {
        housemodel = (DefaultTableModel) tblHouse.getModel();
        housemodel.setRowCount(0);
        
        for (House house : AllSystem.houses) {
            Object[] row = new Object[2];
            row[0] = house;
            row[1] = house.getOwner();
            
            housemodel.addRow(row);
        }
    }
    
    private void populateTableHospital() {
        hospitalmodel = (DefaultTableModel) tblHospital.getModel();
        hospitalmodel.setRowCount(0);
        
        for (Hospital hospital : AllSystem.hospitals) {
            Object[] row = new Object[1];
            row[0] = hospital;
           
            
            hospitalmodel.addRow(row);
        }
        
    }


}
