/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.AllSystem;

/**
 *
 * @author evelynzu
 */
public class SystemAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form systemAdminJPanel
     */
    public SystemAdminJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoginPatient = new javax.swing.JButton();
        btnLoginDoctor = new javax.swing.JButton();
        btnLoginCommunityAdmin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(189, 212, 231));

        btnLoginPatient.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLoginPatient.setText("Login as patient");
        btnLoginPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPatientActionPerformed(evt);
            }
        });

        btnLoginDoctor.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLoginDoctor.setText("Login as doctor");
        btnLoginDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginDoctorActionPerformed(evt);
            }
        });

        btnLoginCommunityAdmin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLoginCommunityAdmin.setText("Login as community admin");
        btnLoginCommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginCommunityAdminActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton1.setText("Login as SystemAdmin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoginDoctor)
                .addGap(392, 392, 392))
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoginCommunityAdmin)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnLoginPatient)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(17, 17, 17)))))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnLoginDoctor)
                .addGap(37, 37, 37)
                .addComponent(btnLoginPatient)
                .addGap(36, 36, 36)
                .addComponent(btnLoginCommunityAdmin)
                .addGap(95, 95, 95)
                .addComponent(jButton1)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPatientActionPerformed
        PatientJFrame patientJFrame = new PatientJFrame(AllSystem.patient1);
        patientJFrame.setVisible(true);
    }//GEN-LAST:event_btnLoginPatientActionPerformed

    private void btnLoginDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginDoctorActionPerformed
        DoctorJFrame doctorJFrame = new DoctorJFrame(AllSystem.doctor1);
                    doctorJFrame.setVisible(true);
                    
    }//GEN-LAST:event_btnLoginDoctorActionPerformed

    private void btnLoginCommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginCommunityAdminActionPerformed
        CommunityAdminJFrame communityAdminJFrame = new CommunityAdminJFrame(AllSystem.communityAdmin1);
        communityAdminJFrame.setVisible(true);
    }//GEN-LAST:event_btnLoginCommunityAdminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SystemAdminJFrame systemAdminJFrame = new SystemAdminJFrame();
        systemAdminJFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginCommunityAdmin;
    private javax.swing.JButton btnLoginDoctor;
    private javax.swing.JButton btnLoginPatient;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
